set(CONFIG_PACKAGE_NAME "triCheckedUpdater" CACHE STRING "")
set(CONFIG_PACKAGE_FILENAME "triCheckedUpdater" CACHE STRING "")

set(CONFIG_TYCMD_BUILD OFF CACHE BOOL "")
set(CONFIG_TYCOMMANDER_BUILD OFF CACHE BOOL "")

set(CONFIG_TYUPDATER_EXECUTABLE "triChecked Updater" CACHE STRING "")
set(CONFIG_TYUPDATER_NAME "triChecked Updater" CACHE STRING "")

set(CONFIG_URL_WEBSITE "http://trichecked.de/" CACHE STRING "")
set(CONFIG_URL_BUGS "" CACHE STRING "")
